STL_DIR=../stl
AMF_DIR=../amf
IMG_DIR=../img
SRC_DIR=../print_plates
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../
OUTPUT_FOLDER=cad
NAME_PREFIX=TF-MOTORSCALE
PROCESSOR3D_PARAM=--force --no_stl

include ../../utils/Makefile
